export interface Game {
  id: string;
  rank: number;
  title: string;
  categories: string[];
  platforms: ('pc' | 'ps5' | 'xbox' | 'switch')[];
  bannerUrl: string;
  statLabel: string;
  statValue: string;
  statChangePercent: number;
  rankChange?: number; // Positive for up, negative for down, 0 or undefined for no change
  featuredComment?: string;
}

export const topActiveGamesData: Game[] = [
  {
    id: 'elden-ring',
    rank: 1,
    title: 'Elden Ring',
    categories: ['Action RPG', 'Open World'],
    platforms: ['pc', 'ps5', 'xbox'],
    bannerUrl: 'https://placehold.co/160x80/png?text=EldenRingBanner',
    statLabel: 'Avg Players',
    statValue: '750K',
    rankChange: 2,
    featuredComment: '"Vast world, endless discovery!"',
    statChangePercent: 15,
  },
  {
    id: 'baldurs-gate-3',
    rank: 2,
    title: "Baldur's Gate 3",
    categories: ['RPG', 'Turn-based'],
    platforms: ['pc', 'ps5'],
    bannerUrl: 'https://placehold.co/160x80/png?text=BG3Banner',
    statLabel: 'Avg Players',
    statValue: '520K',
    rankChange: -1,
    featuredComment: '"Incredible story and choices."',
    statChangePercent: -5,
  },
  {
    id: 'helldivers-2',
    rank: 3,
    title: 'Helldivers 2',
    categories: ['Shooter', 'Co-op'],
    platforms: ['pc', 'ps5'],
    bannerUrl: 'https://placehold.co/160x80/png?text=HelldiversBanner',
    statLabel: 'Avg Players',
    statValue: '450K',
    rankChange: 0,
    featuredComment: '"FOR DEMOCRACY! Best co-op ever."',
    statChangePercent: 0,
  },
  {
    id: 'cyberpunk-2077',
    rank: 4,
    title: 'Cyberpunk 2077',
    categories: ['Action RPG', 'Open World'],
    platforms: ['pc', 'ps5', 'xbox'],
    bannerUrl: 'https://placehold.co/160x80/png?text=CyberpunkBanner',
    statLabel: 'Avg Players',
    statValue: '350K',
    rankChange: 5,
    featuredComment: '"Night City is breathtaking now."',
    statChangePercent: 25,
  },
  {
    id: 'zelda-totk',
    rank: 5,
    title: 'Zelda: Tears of the Kingdom',
    categories: ['Action-Adventure', 'Open World'],
    platforms: ['switch'],
    bannerUrl: 'https://placehold.co/160x80/png?text=ZeldaBanner',
    statLabel: 'Avg Players',
    statValue: '120k',
    rankChange: -3,
    featuredComment: '"Hyrule feels brand new again!"',
    statChangePercent: -8,
  },
];

export const topRatedGamesData: Game[] = [
  {
    id: 'red-dead-2',
    rank: 1,
    title: 'Red Dead Redemption 2',
    categories: ['Action-Adventure', 'Open World'],
    platforms: ['pc', 'ps5', 'xbox'],
    bannerUrl: 'https://placehold.co/160x80/png?text=RDR2Banner',
    statLabel: 'Rating',
    statValue: '9.8 / 10',
    rankChange: 1,
    featuredComment: '"Masterpiece of storytelling and world-building."',
    statChangePercent: 2,
  },
  {
    id: 'witcher-3',
    rank: 2,
    title: 'The Witcher 3: Wild Hunt',
    categories: ['Action RPG', 'Open World'],
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    bannerUrl: 'https://placehold.co/160x80/png?text=Witcher3Banner',
    statLabel: 'Rating',
    statValue: '9.7 / 10',
    rankChange: 0,
    featuredComment: '"A benchmark for modern RPGs."',
    statChangePercent: 0,
  },
  {
    id: 'god-of-war-ragnarok',
    rank: 3,
    title: 'God of War Ragnarök',
    categories: ['Action-Adventure', 'Narrative'],
    platforms: ['ps5'],
    bannerUrl: 'https://placehold.co/160x80/png?text=GoWRagnarokBanner',
    statLabel: 'Rating',
    statValue: '9.6 / 10',
    rankChange: -1,
    featuredComment: '"Epic conclusion to a beloved saga."',
    statChangePercent: -1,
  },
  {
    id: 'hades',
    rank: 4,
    title: 'Hades',
    categories: ['Roguelike', 'Action RPG'],
    platforms: ['pc', 'switch', 'ps5', 'xbox'],
    bannerUrl: 'https://placehold.co/160x80/png?text=HadesBanner',
    statLabel: 'Rating',
    statValue: '9.5 / 10',
    rankChange: 1,
    featuredComment: '"Addictive gameplay loop and amazing story."',
    statChangePercent: 1,
  },
  {
    id: 'persona-5-royal',
    rank: 5,
    title: 'Persona 5 Royal',
    categories: ['JRPG', 'Social Sim'],
    platforms: ['ps5', 'pc', 'xbox', 'switch'],
    bannerUrl: 'https://placehold.co/160x80/png?text=P5RBanner',
    statLabel: 'Rating',
    statValue: '9.5 / 10',
    rankChange: 0,
    featuredComment: '"Stylish, deep, and incredibly polished."',
    statChangePercent: 0,
  },
];

export const topSellingGamesData: Game[] = [
  {
    id: 'gta-v',
    rank: 1,
    title: 'Grand Theft Auto V',
    categories: ['Action-Adventure', 'Open World'],
    platforms: ['pc', 'ps5', 'xbox'],
    bannerUrl: 'https://placehold.co/160x80/png?text=GTAVBanner',
    statLabel: 'Copies Sold',
    statValue: '~195M',
    rankChange: 0,
    featuredComment: '"Still selling like crazy after all these years!"',
    statChangePercent: 5,
  },
  {
    id: 'minecraft',
    rank: 2,
    title: 'Minecraft',
    categories: ['Sandbox', 'Survival'],
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    bannerUrl: 'https://placehold.co/160x80/png?text=MinecraftBanner',
    statLabel: 'Copies Sold',
    statValue: '~100M',
    rankChange: 0,
    featuredComment: '"The ultimate creative playground."',
    statChangePercent: 2,
  },
  {
    id: 'pubg',
    rank: 3,
    title: 'PUBG: Battlegrounds',
    categories: ['Battle Royale', 'Shooter'],
    platforms: ['pc', 'xbox', 'ps5'],
    bannerUrl: 'https://placehold.co/160x80/png?text=PUBGBanner',
    statLabel: 'Copies Sold',
    statValue: '~75M',
    rankChange: 1,
    featuredComment: '"The original PC battle royale king."',
    statChangePercent: 10,
  },
  {
    id: 'tetris-various',
    rank: 4,
    title: 'Tetris (Various)',
    categories: ['Puzzle'],
    platforms: ['pc', 'switch', 'ps5', 'xbox'], // Representing its ubiquity
    bannerUrl: 'https://placehold.co/160x80/png?text=TetrisBanner',
    statLabel: 'Copies Sold',
    statValue: '~520M',
    rankChange: 0,
    featuredComment: '"The timeless puzzle classic, sold everywhere."',
    statChangePercent: 1,
  },
  {
    id: 'animal-crossing-nh',
    rank: 5,
    title: 'Animal Crossing: New Horizons',
    categories: ['Life Sim', 'Social'],
    platforms: ['switch'],
    bannerUrl: 'https://placehold.co/160x80/png?text=ACNHBanner',
    statLabel: 'Copies Sold',
    statValue: '~45M',
    rankChange: -1,
    featuredComment: '"The perfect escape during challenging times."',
    statChangePercent: -2,
  },
];
