export interface RankedGame {
  gameId: string;
  period: string; // e.g. '2024-06'
  rankingType:
    | 'overall'
    | 'story'
    | 'graphics'
    | 'gameplay'
    | 'longevity'
    | 'music';

  // ranking score (the actual rating number used to sort this leaderboard)
  score: number; // current rating score for this rankingType
  previousScore: number; // previous period's score for this rankingType
  scoreChange: number; // score delta (score - previousScore)

  // ranking positions
  rank: number; // current rank
  previousRank: number; // previous period rank
  rankChange: number; // rank delta (previousRank - rank)

  // game info snapshot (denormalized for fast read)
  gameName: string;
  bannerUrl: string;
  developer: string;
  genre: string;
  platforms: ('pc' | 'ps5' | 'xbox' | 'switch')[];

  // extra stats
  monthlyActivePlayers: number;
  totalRatings: number;
}

export const mockRankingData: RankedGame[] = [
  // Overall Ranking (Top 5)
  {
    gameId: 'elden-ring',
    period: '2025-06',
    rankingType: 'overall',
    score: 97,
    previousScore: 96,
    scoreChange: 1,
    rank: 1,
    previousRank: 1,
    rankChange: 0,
    gameName: 'ELDEN RING',
    bannerUrl:
      'https://preview.redd.it/znxzjlws0i471.jpg?width=1920&format=pjpg&auto=webp&s=2514f6dd7c16a0ed3aa0c93cd80b134cd8853178',
    developer: 'FromSoftware',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 1050000,
    totalRatings: 850000,
  },
  {
    gameId: 'baldurs-gate-3',
    period: '2025-06',
    rankingType: 'overall',
    score: 95,
    previousScore: 95,
    scoreChange: 0,
    rank: 2,
    previousRank: 2,
    rankChange: 0,
    gameName: "BALDUR'S GATE 3",
    bannerUrl:
      'https://cdn.wccftech.com/wp-content/uploads/2023/08/Baldurs-Gate-3-header-1920x1080.jpg',
    developer: 'Larian Studios',
    genre: 'RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 750000,
    totalRatings: 650000,
  },
  {
    gameId: 'black-myth-wukong',
    period: '2025-06',
    rankingType: 'overall',
    score: 93,
    previousScore: 92,
    scoreChange: 1,
    rank: 3,
    previousRank: 3,
    rankChange: 0,
    gameName: 'Black Myth: Wukong',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/ca9ef1bcf2f54043baac351366aec677/black-myth-wukong-jz9yr.jpg',
    developer: 'Game Science',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 550000,
    totalRatings: 500000,
  },
  {
    gameId: 'slay-the-spire-2',
    period: '2025-06',
    rankingType: 'overall',
    score: 90,
    previousScore: 0,
    scoreChange: 90,
    rank: 4,
    previousRank: 0,
    rankChange: -4,
    gameName: 'Slay the Spire 2',
    bannerUrl: 'https://www.megacrit.com/images/sts2_key_art_16x9-scaled.jpg',
    developer: 'MegaCrit',
    genre: 'Roguelike Deckbuilder',
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    monthlyActivePlayers: 200000,
    totalRatings: 120000,
  },
  {
    gameId: 'wuchang-fallen-feathers',
    period: '2025-06',
    rankingType: 'overall',
    score: 88,
    previousScore: 0,
    scoreChange: 88,
    rank: 5,
    previousRank: 0,
    rankChange: -5,
    gameName: 'WUCHANG: Fallen Feathers',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/61237a4bad9f482a9ad1a1ac74520bba/wuchang-fallen-feathers-199kj.jpg',
    developer: 'Leenzee Games',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 180000,
    totalRatings: 90000,
  },

  // Story Ranking
  {
    gameId: 'baldurs-gate-3',
    period: '2025-06',
    rankingType: 'story',
    score: 98,
    previousScore: 97,
    scoreChange: 1,
    rank: 1,
    previousRank: 1,
    rankChange: 0,
    gameName: "BALDUR'S GATE 3",
    bannerUrl:
      'https://cdn.wccftech.com/wp-content/uploads/2023/08/Baldurs-Gate-3-header-1920x1080.jpg',
    developer: 'Larian Studios',
    genre: 'RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 750000,
    totalRatings: 650000,
  },
  {
    gameId: 'elden-ring',
    period: '2025-06',
    rankingType: 'story',
    score: 95,
    previousScore: 95,
    scoreChange: 0,
    rank: 2,
    previousRank: 2,
    rankChange: 0,
    gameName: 'ELDEN RING',
    bannerUrl:
      'https://preview.redd.it/znxzjlws0i471.jpg?width=1920&format=pjpg&auto=webp&s=2514f6dd7c16a0ed3aa0c93cd80b134cd8853178',
    developer: 'FromSoftware',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 1050000,
    totalRatings: 850000,
  },
  {
    gameId: 'black-myth-wukong',
    period: '2025-06',
    rankingType: 'story',
    score: 92,
    previousScore: 92,
    scoreChange: 0,
    rank: 3,
    previousRank: 3,
    rankChange: 0,
    gameName: 'Black Myth: Wukong',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/ca9ef1bcf2f54043baac351366aec677/black-myth-wukong-jz9yr.jpg',
    developer: 'Game Science',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 550000,
    totalRatings: 500000,
  },
  {
    gameId: 'wuchang-fallen-feathers',
    period: '2025-06',
    rankingType: 'story',
    score: 90,
    previousScore: 0,
    scoreChange: 90,
    rank: 4,
    previousRank: 0,
    rankChange: -4,
    gameName: 'WUCHANG: Fallen Feathers',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/61237a4bad9f482a9ad1a1ac74520bba/wuchang-fallen-feathers-199kj.jpg',
    developer: 'Leenzee Games',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 180000,
    totalRatings: 90000,
  },
  {
    gameId: 'slay-the-spire-2',
    period: '2025-06',
    rankingType: 'story',
    score: 85,
    previousScore: 0,
    scoreChange: 85,
    rank: 5,
    previousRank: 0,
    rankChange: -5,
    gameName: 'Slay the Spire 2',
    bannerUrl: 'https://www.megacrit.com/images/sts2_key_art_16x9-scaled.jpg',
    developer: 'MegaCrit',
    genre: 'Roguelike Deckbuilder',
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    monthlyActivePlayers: 200000,
    totalRatings: 120000,
  },

  // Graphics Ranking
  {
    gameId: 'black-myth-wukong',
    period: '2025-06',
    rankingType: 'graphics',
    score: 99,
    previousScore: 98,
    scoreChange: 1,
    rank: 1,
    previousRank: 1,
    rankChange: 0,
    gameName: 'Black Myth: Wukong',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/ca9ef1bcf2f54043baac351366aec677/black-myth-wukong-jz9yr.jpg',
    developer: 'Game Science',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 550000,
    totalRatings: 500000,
  },
  {
    gameId: 'elden-ring',
    period: '2025-06',
    rankingType: 'graphics',
    score: 96,
    previousScore: 96,
    scoreChange: 0,
    rank: 2,
    previousRank: 2,
    rankChange: 0,
    gameName: 'ELDEN RING',
    bannerUrl:
      'https://preview.redd.it/znxzjlws0i471.jpg?width=1920&format=pjpg&auto=webp&s=2514f6dd7c16a0ed3aa0c93cd80b134cd8853178',
    developer: 'FromSoftware',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 1050000,
    totalRatings: 850000,
  },
  {
    gameId: 'wuchang-fallen-feathers',
    period: '2025-06',
    rankingType: 'graphics',
    score: 94,
    previousScore: 0,
    scoreChange: 94,
    rank: 3,
    previousRank: 0,
    rankChange: -3,
    gameName: 'WUCHANG: Fallen Feathers',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/61237a4bad9f482a9ad1a1ac74520bba/wuchang-fallen-feathers-199kj.jpg',
    developer: 'Leenzee Games',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 180000,
    totalRatings: 90000,
  },
  {
    gameId: 'baldurs-gate-3',
    period: '2025-06',
    rankingType: 'graphics',
    score: 93,
    previousScore: 93,
    scoreChange: 0,
    rank: 4,
    previousRank: 4,
    rankChange: 0,
    gameName: "BALDUR'S GATE 3",
    bannerUrl:
      'https://cdn.wccftech.com/wp-content/uploads/2023/08/Baldurs-Gate-3-header-1920x1080.jpg',
    developer: 'Larian Studios',
    genre: 'RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 750000,
    totalRatings: 650000,
  },
  {
    gameId: 'slay-the-spire-2',
    period: '2025-06',
    rankingType: 'graphics',
    score: 85,
    previousScore: 0,
    scoreChange: 85,
    rank: 5,
    previousRank: 0,
    rankChange: -5,
    gameName: 'Slay the Spire 2',
    bannerUrl: 'https://www.megacrit.com/images/sts2_key_art_16x9-scaled.jpg',
    developer: 'MegaCrit',
    genre: 'Roguelike Deckbuilder',
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    monthlyActivePlayers: 200000,
    totalRatings: 120000,
  },

  // Gameplay Ranking
  {
    gameId: 'elden-ring',
    period: '2025-06',
    rankingType: 'gameplay',
    score: 98,
    previousScore: 98,
    scoreChange: 0,
    rank: 1,
    previousRank: 1,
    rankChange: 0,
    gameName: 'ELDEN RING',
    bannerUrl:
      'https://preview.redd.it/znxzjlws0i471.jpg?width=1920&format=pjpg&auto=webp&s=2514f6dd7c16a0ed3aa0c93cd80b134cd8853178',
    developer: 'FromSoftware',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 1050000,
    totalRatings: 850000,
  },
  {
    gameId: 'black-myth-wukong',
    period: '2025-06',
    rankingType: 'gameplay',
    score: 96,
    previousScore: 95,
    scoreChange: 1,
    rank: 2,
    previousRank: 2,
    rankChange: 0,
    gameName: 'Black Myth: Wukong',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/ca9ef1bcf2f54043baac351366aec677/black-myth-wukong-jz9yr.jpg',
    developer: 'Game Science',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 550000,
    totalRatings: 500000,
  },
  {
    gameId: 'slay-the-spire-2',
    period: '2025-06',
    rankingType: 'gameplay',
    score: 94,
    previousScore: 0,
    scoreChange: 94,
    rank: 3,
    previousRank: 0,
    rankChange: -3,
    gameName: 'Slay the Spire 2',
    bannerUrl: 'https://www.megacrit.com/images/sts2_key_art_16x9-scaled.jpg',
    developer: 'MegaCrit',
    genre: 'Roguelike Deckbuilder',
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    monthlyActivePlayers: 200000,
    totalRatings: 120000,
  },
  {
    gameId: 'baldurs-gate-3',
    period: '2025-06',
    rankingType: 'gameplay',
    score: 93,
    previousScore: 93,
    scoreChange: 0,
    rank: 4,
    previousRank: 4,
    rankChange: 0,
    gameName: "BALDUR'S GATE 3",
    bannerUrl:
      'https://cdn.wccftech.com/wp-content/uploads/2023/08/Baldurs-Gate-3-header-1920x1080.jpg',
    developer: 'Larian Studios',
    genre: 'RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 750000,
    totalRatings: 650000,
  },
  {
    gameId: 'wuchang-fallen-feathers',
    period: '2025-06',
    rankingType: 'gameplay',
    score: 90,
    previousScore: 0,
    scoreChange: 90,
    rank: 5,
    previousRank: 0,
    rankChange: -5,
    gameName: 'WUCHANG: Fallen Feathers',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/61237a4bad9f482a9ad1a1ac74520bba/wuchang-fallen-feathers-199kj.jpg',
    developer: 'Leenzee Games',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 180000,
    totalRatings: 90000,
  },

  // Longevity Ranking
  {
    gameId: 'elden-ring',
    period: '2025-06',
    rankingType: 'longevity',
    score: 97,
    previousScore: 97,
    scoreChange: 0,
    rank: 1,
    previousRank: 1,
    rankChange: 0,
    gameName: 'ELDEN RING',
    bannerUrl:
      'https://preview.redd.it/znxzjlws0i471.jpg?width=1920&format=pjpg&auto=webp&s=2514f6dd7c16a0ed3aa0c93cd80b134cd8853178',
    developer: 'FromSoftware',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 1050000,
    totalRatings: 850000,
  },
  {
    gameId: 'baldurs-gate-3',
    period: '2025-06',
    rankingType: 'longevity',
    score: 95,
    previousScore: 95,
    scoreChange: 0,
    rank: 2,
    previousRank: 2,
    rankChange: 0,
    gameName: "BALDUR'S GATE 3",
    bannerUrl:
      'https://cdn.wccftech.com/wp-content/uploads/2023/08/Baldurs-Gate-3-header-1920x1080.jpg',
    developer: 'Larian Studios',
    genre: 'RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 750000,
    totalRatings: 650000,
  },
  {
    gameId: 'black-myth-wukong',
    period: '2025-06',
    rankingType: 'longevity',
    score: 92,
    previousScore: 91,
    scoreChange: 1,
    rank: 3,
    previousRank: 3,
    rankChange: 0,
    gameName: 'Black Myth: Wukong',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/ca9ef1bcf2f54043baac351366aec677/black-myth-wukong-jz9yr.jpg',
    developer: 'Game Science',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 550000,
    totalRatings: 500000,
  },
  {
    gameId: 'slay-the-spire-2',
    period: '2025-06',
    rankingType: 'longevity',
    score: 90,
    previousScore: 0,
    scoreChange: 90,
    rank: 4,
    previousRank: 0,
    rankChange: -4,
    gameName: 'Slay the Spire 2',
    bannerUrl: 'https://www.megacrit.com/images/sts2_key_art_16x9-scaled.jpg',
    developer: 'MegaCrit',
    genre: 'Roguelike Deckbuilder',
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    monthlyActivePlayers: 200000,
    totalRatings: 120000,
  },
  {
    gameId: 'wuchang-fallen-feathers',
    period: '2025-06',
    rankingType: 'longevity',
    score: 88,
    previousScore: 0,
    scoreChange: 88,
    rank: 5,
    previousRank: 0,
    rankChange: -5,
    gameName: 'WUCHANG: Fallen Feathers',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/61237a4bad9f482a9ad1a1ac74520bba/wuchang-fallen-feathers-199kj.jpg',
    developer: 'Leenzee Games',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 180000,
    totalRatings: 90000,
  },

  // Music Ranking
  {
    gameId: 'elden-ring',
    period: '2025-06',
    rankingType: 'music',
    score: 98,
    previousScore: 97,
    scoreChange: 1,
    rank: 1,
    previousRank: 1,
    rankChange: 0,
    gameName: 'ELDEN RING',
    bannerUrl:
      'https://preview.redd.it/znxzjlws0i471.jpg?width=1920&format=pjpg&auto=webp&s=2514f6dd7c16a0ed3aa0c93cd80b134cd8853178',
    developer: 'FromSoftware',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 1050000,
    totalRatings: 850000,
  },
  {
    gameId: 'black-myth-wukong',
    period: '2025-06',
    rankingType: 'music',
    score: 95,
    previousScore: 94,
    scoreChange: 1,
    rank: 2,
    previousRank: 2,
    rankChange: 0,
    gameName: 'Black Myth: Wukong',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/ca9ef1bcf2f54043baac351366aec677/black-myth-wukong-jz9yr.jpg',
    developer: 'Game Science',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 550000,
    totalRatings: 500000,
  },
  {
    gameId: 'baldurs-gate-3',
    period: '2025-06',
    rankingType: 'music',
    score: 94,
    previousScore: 94,
    scoreChange: 0,
    rank: 3,
    previousRank: 3,
    rankChange: 0,
    gameName: "BALDUR'S GATE 3",
    bannerUrl:
      'https://cdn.wccftech.com/wp-content/uploads/2023/08/Baldurs-Gate-3-header-1920x1080.jpg',
    developer: 'Larian Studios',
    genre: 'RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 750000,
    totalRatings: 650000,
  },
  {
    gameId: 'wuchang-fallen-feathers',
    period: '2025-06',
    rankingType: 'music',
    score: 90,
    previousScore: 0,
    scoreChange: 90,
    rank: 4,
    previousRank: 0,
    rankChange: -4,
    gameName: 'WUCHANG: Fallen Feathers',
    bannerUrl:
      'https://cdn1.epicgames.com/spt-assets/61237a4bad9f482a9ad1a1ac74520bba/wuchang-fallen-feathers-199kj.jpg',
    developer: 'Leenzee Games',
    genre: 'Action RPG',
    platforms: ['pc', 'ps5', 'xbox'],
    monthlyActivePlayers: 180000,
    totalRatings: 90000,
  },
  {
    gameId: 'slay-the-spire-2',
    period: '2025-06',
    rankingType: 'music',
    score: 88,
    previousScore: 0,
    scoreChange: 88,
    rank: 5,
    previousRank: 0,
    rankChange: -5,
    gameName: 'Slay the Spire 2',
    bannerUrl: 'https://www.megacrit.com/images/sts2_key_art_16x9-scaled.jpg',
    developer: 'MegaCrit',
    genre: 'Roguelike Deckbuilder',
    platforms: ['pc', 'ps5', 'xbox', 'switch'],
    monthlyActivePlayers: 200000,
    totalRatings: 120000,
  },
];
